version: "3"

services:
  db:
    image: postgres:${POSTGRES_VERSION:-12}
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-sketch}
    volumes:
    - ./devops/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "${DB_HOST:-127.0.0.1}:${DB_PORT:-54321}:5432"
    command: ["postgres", "-c", "log_statement=all"]
